# 生产环境配置
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:xu_news_rag}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50

faiss:
  index-path: ./data/faiss_index
  dimension: 768

ollama:
  base-url: ${OLLAMA_URL:http://192.168.171.1:11434}
  model:
    llm: qwen3:0.6b
    embedding: ${OLLAMA_EMBEDDING_MODEL:nomic-embed-text:latest}
  timeout: 60000

# 重排模型配置
reranker:
  enabled: ${RERANKER_ENABLED:true}
  base-url: ${RERANKER_URL:https://api.siliconflow.cn}
  api-key: ${RERANKER_API_KEY:}
  model: BAAI/bge-reranker-v2-m3
  candidate-multiplier: 4

n8n:
  base-url: ${N8N_URL:http://n8n:5678}
  api-key: ${N8N_API_KEY}

logging:
  level:
    root: INFO
    com.xu.news: INFO
    com.baomidou.mybatisplus: WARN
  file:
    name: /var/log/xu-news-rag/application.log

