server:
  port: 8081

spring:
  application:
    name: xu-news-ai-rag-test

  # 测试数据源配置 - 使用H2内存数据库
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_xu_news_rag;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: TestHikariCP
      max-lifetime: 600000
      connection-timeout: 10000

  # H2数据库配置
  h2:
    console:
      enabled: true
      path: /h2-console

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xu.news.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置 - 测试环境
jwt:
  secret: TEST_SECRET_KEY_FOR_UNIT_TESTING_XU_NEWS_AI_RAG_2025_VERY_LONG_STRING
  expiration: 3600000  # 1小时
  header: Authorization
  prefix: Bearer 

# 文件存储配置 - 测试环境
file:
  upload-dir: ./test-uploads
  allowed-extensions: pdf,doc,docx,txt,md
  max-size: 10485760  # 10MB

# FAISS向量库配置 - 测试环境
faiss:
  index-path: ./test-data/faiss_index
  dimension: 768

# Ollama配置 - 测试环境（Mock）
ollama:
  base-url: http://localhost:11434
  model:
    llm: qwen3:0.6b
    embedding: nomic-embed-text:latest
  timeout: 30000

# n8n集成配置 - 测试环境（Mock）
n8n:
  base-url: http://localhost:5678
  webhook-path: /webhook
  api-key: test-api-key

# 日志配置 - 测试环境
logging:
  level:
    root: WARN
    com.xu.news: DEBUG
    org.springframework.test: DEBUG
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

# 应用配置
app:
  name: XU-News-AI-RAG-Test
  version: 1.0.0-TEST
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    allow-credentials: true
  security:
    ignore-urls:
      - /auth/login
      - /auth/register
      - /auth/health
      - /h2-console/**

