server:
  port: 8081

spring:
  application:
    name: xu-news-ai-rag-test

  # 使用H2内存数据库
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=USER
    username: sa
    password:
  
  # H2控制台
  h2:
    console:
      enabled: true
  
  # SQL初始化
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: false

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  # 禁用Security（测试环境）
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xu.news.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: TEST_SECRET_KEY_FOR_UNIT_TESTING_XU_NEWS_AI_RAG_2025_VERY_LONG_STRING_MINIMUM_256_BITS
  expiration: 3600000
  header: Authorization
  prefix: Bearer

# FAISS配置
faiss:
  index-path: ./test-data/faiss
  dimension: 768

# Ollama配置（测试环境Mock）
ollama:
  base-url: http://localhost:11434
  model:
    llm: qwen3:0.6b
    embedding: nomic-embed-text:latest
  timeout: 30000

# Reranker配置（测试环境禁用）
reranker:
  enabled: false
  base-url: http://localhost:8080
  api-key: test-key
  model: test-model
  top-n: 5
  candidate-multiplier: 4

# 日志配置
logging:
  level:
    root: WARN
    com.xu.news: INFO
    org.springframework: WARN
    org.mybatis: WARN
